name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Verify Cypress install
        run: npx cypress verify

      - name: Run Cypress tests in Chrome
        run: npx cypress run --browser chrome

      # Optional: Upload screenshots/videos ONLY if tests fail
      - name: Collect Cypress artifacts if failed
        if: failure()
        run: |
          mkdir -p upload
          if [ -d cypress/screenshots ]; then cp -r cypress/screenshots upload/; fi
          if [ -d cypress/videos ]; then cp -r cypress/videos upload/; fi
        continue-on-error: true

      - name: Upload Cypress test artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: upload/